<?php

use Magento\Framework\Escaper;
use Vendor\Module\ViewModel\GetAttribute;
use Magento\Customer\Block\Account\Dashboard\Info;

/**
 * @var Info $block
 * @var Escaper $escaper
 * @var GetAttribute $viewModel
 */

$viewModel = $block->getViewModel();
?>
<form class="form manage" method="POST" action="<?= $this->getUrl('module/account/save'); ?>" id="mcf" >
    <fieldset class="fieldset">
        <div class="field choice">
            <select name="hobby" id="hobby">
                <?php foreach ($viewModel->getHobbyOptions() as $option): ?>
                    <option value="<?= $escaper->escapeHtml($option['value']);?>"
                    <?php if ($block->getCustomer()->getCustomAttribute('hobby')->getValue() === $option['value']): ?>
                        selected <?php endif ?>>
                        <?= $escaper->escapeHtml($option['label']);?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    id="hobby-submit"
                    title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"
                    class="action save primary">
                <span><?= $escaper->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
    </div>
</form>



